

# Fichier qui détermine la rigueur de Flutter lorsqu'il analyse le code
# source : https://codelabs.developers.google.com/codelabs/flutter-codelab-first?hl=fr#2

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false